[build]
  command = """
    cd frontend && npm install && npm run build
  """
  publish = "frontend/build"  # Adjust the path to your built frontend files

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
